services:
  db:
    image: mysql:8.0
    container_name: carrinho_compras_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: carrinho_compras
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    build:
      context: ./docker/php
    container_name: carrinho_compras_api
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./api:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:stable
    container_name: carrinho_compras_web
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      - ./api:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data:
