/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CartButton: typeof import('./src/components/CartButton.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    PaginationControls: typeof import('./src/components/PaginationControls.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchToolbar: typeof import('./src/components/SearchToolbar.vue')['default']
  }
}
